name: Waka Readme

on:
  workflow_dispatch:
    inputs:
        name:
          description: 'Person to greet'
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: anmol098/waka-readme-stats@V1.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "pt"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "True"
